---
name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: container build
        run: make build
      - name: container push
        run: make push
...
